image: node:10.15.1

pipelines:
  branches:
    master:
      - step:
          name: Run Build
          caches:
            - node
          script:
            - yarn
            - yarn build
          artifacts:
            - dist/**
      - step:
          name: Deploy to Test Server
          deployment: test
          script:
            - export APP_BUILD=$(date +%s)
            - scp -r dist/ deploy@app.dev.staffing.dog:/home/deploy/$(printenv APP_BUILD)
            - ssh deploy@app.dev.staffing.dog ln -sfn /home/deploy/$(printenv APP_BUILD) /var/www/app
    alpha:
      - step:
          name: Run Build
          caches:
            - node
          script:
            - yarn
            - yarn build
          artifacts:
            - dist/**
      - step:
          name: Deploy to Production Server
          deployment: Production
          script:
            - export APP_BUILD=$(date +%s)
            - scp -r dist/ deploy@178.128.70.108:/home/deploy/$(printenv APP_BUILD)
            - ssh deploy@178.128.70.108 ln -sfn /home/deploy/$(printenv APP_BUILD) /var/www/app