describe('onboarding navigation', () => {
  it('can navigate to step 1,2,3,complete and prev', () => {
    cy.visit('/#/onboarding')
      .getByText(/Let's Get Started/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/1')
      .getByText(/First Name/)
      .siblings('input')
      .type('Keanu')
      .should('have.value', 'Keanu')
      .getByText(/Last Name/)
      .siblings('input')
      .type('Reeves')
      .should('have.value', 'Reeves')
      .getByText(/Email Address/)
      .siblings('input')
      .type('neo@staffing.dog')
      .should('have.value', 'neo@staffing.dog')
      .getByText(/Password/)
      .siblings('input')
      .type('abc12345K')
      .should('have.value', 'abc12345K')
      .getByText(/Verify Password/)
      .siblings('input')
      .type('abc12345K')
      .should('have.value', 'abc12345K')
      .getByText(/Next Step/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/2')
      .getByText(/Previous/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/1')
      .getByText(/Next Step/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/2')
      .getByText('Street Address')
      .siblings('input')
      .type('123 fake street')
      .should('have.value', '123 fake street')
      .getByText('State')
      .siblings('input')
      .type('Utah')
      .should('have.value', 'Utah')
      .getByText('City')
      .siblings('input')
      .type('SLC')
      .should('have.value', 'SLC')
      .getByText('Postal Code')
      .siblings('input')
      .type('84102')
      .should('have.value', '84102')
      .getByText(/Next Step/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/3')
      .getByText(/Previous/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/2')
      .getByText(/Next Step/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/3')
      .get('[id*=react-select]')
      .eq(0)
      .type('Dentist', {
        force: true,
      })
      .type('{enter}', {
        force: true,
      })
      .get('[id*=react-select]')
      .eq(2)
      .type('All', {
        force: true,
      })
      .type('{enter}', {
        force: true,
      })
      .getByText(/Next Step/)
      .click()
      .url()
      .should('include', 'onboarding/professional/step/complete')
  })
})
